### ISSUE TITLE
SomaticThresholdVariantCallerSuite fails when run after DistributedUtilSuite

### ISSUE THREAD

**Issue by ryan-williams** [hammerlab/guacamole#182]
This command passes:

    mvn -Dsuites="*SomaticThresholdVariantCallerSuite,*DistributedUtilSuite" test

This command sees `SomaticThresholdVariantCallerSuite` fail:

    mvn -Dsuites="*DistributedUtilSuite,*SomaticThresholdVariantCallerSuite" test

Sample error output for `SomaticThresholdVariantCallerSuite`:

```
SomaticThresholdVariantCallerSuite:
--> [2.77 sec. later]: Loaded 56,823 tumor mapped non-duplicate MdTag-containing reads into 1 partitions.
--> [1.32 sec. later]: Loaded 56,478 normal mapped non-duplicate MdTag-containing reads into 1 partitions.
--> [0.00 sec. later]: Including 100,000 loci across 1 contig(s): 20:100000-200000
--> [0.00 sec. later]: Splitting loci by region depth among 20 tasks using 5,000 micro partitions.
--> [0.00 sec. later]: Splitting loci evenly among 5,000 tasks = ~20 loci per task
--> [0.02 sec. later]: Done calculating micro partitions.
--> [0.04 sec. later]: Collecting region counts for RDD 1 of 2.
--> [0.23 sec. later]: Collecting region counts for RDD 2 of 2.
--> [0.13 sec. later]: Done collecting region counts. Total regions with micro partition overlaps: 358,360 = ~17,918 regions per task.
--> [0.00 sec. later]: Regions per micro partition: min=3 mean=72 max=136.
--> [0.07 sec. later]: Loci partitioning: 20:100000-107140=0,20:107140-111944=1,20:111944-116076=2,20:116076-120921=3,20:120921-126827=4,20:126827-131223=5,20:131223-137430=6,20:137430-142066=7,20:142066-148261=8,20:148261-153334=9,20:153334-157493=10,20:157493-162582=11,20:162582-167239=12,20:167239-171407=13,20:171407-175387=14,20:175387-180092=15,20:180092-184310=16,20:184310-189991=17,20:189991-194456=18,20:194456-200000=19
--> [0.02 sec. later]: Writing genotypes to VCF file: /tmp/somatic.threshold.chr20.vcf.
2014-09-25 16:54:04 WARN  ADAMVariationContext:81 - Setting header for partition 0
2014-09-25 16:54:04 WARN  ADAMVariationContext:87 - Set VCF header for partition 0
*** Delayed Messages ***
Region counts: filtered 3 total regions to 3 relevant regions, expanded for overlaps by 300.00% to 12
Regions per task: min=3 25%=3 median=3 (mean=3) 75%=3 max=3. Max is 0.00% more than mean.
Region counts: filtered 3 total regions to 3 relevant regions, expanded for overlaps by 400.00% to 15
Regions per task: min=3 25%=3 median=3 (mean=3) 75%=3 max=3. Max is 0.00% more than mean.
Region counts: filtered 3 total regions to 3 relevant regions, expanded for overlaps by 0.00% to 3
Regions per task: min=0 25%=0 median=0 (mean=1) 75%=2 max=3. Max is 400.00% more than mean.
Region counts: filtered 10 total regions to 10 relevant regions, expanded for overlaps by 0.00% to 10
Regions per task: min=10 25%=10 median=10 (mean=10) 75%=10 max=10. Max is 0.00% more than mean.
Region counts: filtered 3 total regions to 3 relevant regions, expanded for overlaps by 400.00% to 15
Regions per task: min=3 25%=3 median=3 (mean=3) 75%=3 max=3. Max is 0.00% more than mean.
Region counts: filtered 10 total regions to 10 relevant regions, expanded for overlaps by 650.00% to 75
- somatic threshold *** FAILED ***
  java.lang.AssertionError: assertion failed
  at scala.Predef$.assert(Predef.scala:165)
  at org.bdgenomics.guacamole.DistributedUtil$$anonfun$windowTaskFlatMapMultipleRDDs$2.apply(DistributedUtil.scala:480)
  at org.bdgenomics.guacamole.DistributedUtil$$anonfun$windowTaskFlatMapMultipleRDDs$2.apply(DistributedUtil.scala:478)
  at org.bdgenomics.guacamole.DelayedMessages.print(DelayedMessages.scala:23)
  at org.bdgenomics.guacamole.callers.SomaticThresholdVariantCaller$.runWrapper(SomaticThresholdVariantCaller.scala:101)
  at org.bdgenomics.guacamole.callers.SomaticThresholdVariantCallerSuite$$anonfun$1.apply$mcV$sp(SomaticThresholdVariantCallerSuite.scala:13)
  at org.bdgenomics.guacamole.TestUtil$SparkFunSuite$$anonfun$sparkTest$1.apply$mcV$sp(TestUtil.scala:255)
  at org.bdgenomics.guacamole.TestUtil$SparkFunSuite$$anonfun$sparkTest$1.apply(TestUtil.scala:251)
  at org.bdgenomics.guacamole.TestUtil$SparkFunSuite$$anonfun$sparkTest$1.apply(TestUtil.scala:251)
  at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
  ...
```

The crashing line, [`DistributedUtil:480`](https://github.com/hammerlab/guacamole/blob/2f6ad23a6956f5af9143dc4a3303331004ef0fa0/src/main/scala/org/bdgenomics/guacamole/DistributedUtil.scala#L480), is:

    assert(regionsByTask.value.size == numTasks)

**Comment by arahuja** [comment]
@ryan-williams This seems to work for me and the tests path both ways, can you confirm you see the same?

**Comment by ryan-williams** [comment]
Yea working for me in both orders, will close for now
