### ISSUE TITLE
Adam/Guacamole Guava version mismatch

### ISSUE THREAD

**Issue by danvk** [hammerlab/guacamole#309]
When I run my Guacamole job on the cluster, I get the [following error][2]:

```
15/06/26 18:35:04 ERROR yarn.ApplicationMaster: User class threw exception: java.lang.NoSuchMethodError: com.google.common.base.Equivalence.equals()Lcom/google/common/base/Equivalence;
java.lang.NoSuchMethodError: com.google.common.base.Equivalence.equals()Lcom/google/common/base/Equivalence;
	at org.bdgenomics.guavarelocated.collect.Interners$WeakInterner.<init>(Interners.java:68)
	at org.bdgenomics.guavarelocated.collect.Interners$WeakInterner.<init>(Interners.java:66)
	at org.bdgenomics.guavarelocated.collect.Interners.newWeakInterner(Interners.java:63)
	at com.netflix.servo.tag.Tags.<clinit>(Tags.java:26)
	at org.bdgenomics.utils.instrumentation.Metrics$.<init>(Metrics.scala:81)
	at org.bdgenomics.utils.instrumentation.Metrics$.<clinit>(Metrics.scala)
	at org.bdgenomics.adam.rdd.ADAMContext.adamLoad(ADAMContext.scala:171)
	at org.hammerlab.guacamole.reads.Read$.loadReadRDDAndSequenceDictionaryFromADAM(Read.scala:365)
	at org.hammerlab.guacamole.reads.Read$.loadReadRDDAndSequenceDictionary(Read.scala:298)
	at org.hammerlab.guacamole.ReadSet$.apply(ReadSet.scala:96)
	at org.hammerlab.guacamole.Common$.loadReadsFromArguments(Common.scala:146)
	at org.hammerlab.guacamole.commands.StructuralVariant$Caller$.run(StructuralVariantCaller.scala:89)
	at org.hammerlab.guacamole.commands.StructuralVariant$Caller$.run(StructuralVariantCaller.scala:33)
	at org.hammerlab.guacamole.SparkCommand.run(Command.scala:55)
	at org.hammerlab.guacamole.Command.run(Command.scala:46)
	at org.hammerlab.guacamole.Guacamole$.main(Guacamole.scala:68)
	at org.hammerlab.guacamole.Guacamole.main(Guacamole.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:483)
```

Some Googling indicates that this is due to a [Guava version mismatch][1].

When I run `mvn dependency:tree` on an unmodified Guacamole, I get this:

```
[INFO] org.hammerlab.guacamole:guacamole:jar:0.0.1-SNAPSHOT
[INFO] +- com.google.guava:guava:jar:18.0:compile
```

If I comment out the direct guava dependency, I see this:

```
[INFO] org.hammerlab.guacamole:guacamole:jar:0.0.1-SNAPSHOT
[INFO] +- args4j:args4j:jar:2.32:compile
[INFO] +- org.bdgenomics.adam:adam-core:jar:0.16.0:compile
...
[INFO] |  \- com.google.guava:guava:jar:14.0.1:compile
```

The tests all pass when I build Guacamole this way, but I still get the same error when I run jobs on the cluster using the resulting JAR.

[1]: http://stackoverflow.com/questions/24745349/java-lang-nosuchmethoderror-com-google-common-base-equivalence-equals-excepti
[2]: http://demeter-mgmt1.demeter.hpc.mssm.edu:19888/jobhistory/logs/demeter-csmaz10-4.demeter.hpc.mssm.edu:8041/container_1432740718700_2491_01_000009/container_1432740718700_2491_01_000009/vanded03

**Comment by danvk** [comment]
Changing the Guac dependency in `pom.xml` to 14.0.1 has no effect -- it still builds and the tests pass, but I get the [same error][1] on the cluster.

[1]: https://hue.demeter.hpc.mssm.edu/jobbrowser/jobs/application_1432740718700_2493

**Comment by danvk** [comment]
When I run this JAR locally (using `spark-submit --master 'local[*]'`) everything works fine. It's only when I run it on the cluster that I get the strange error.

**Comment by danvk** [comment]
I'm seeing the same behavior when I run `germline-threshold`—it's nothing in my code that's causing this.

**Comment by ryan-williams** [comment]
from some chatting offline, working hypothesis is that this might be related to guac currently only shading `com.google.common.collect.**` rather than all of guava. it seems strange that this stack trace has guac's shaded guava calling back into regular guava, which could be / is coming from some other dep, seemingly working against the point of shading guava in the first place
