### ISSUE TITLE
failed to register classes with Kryo

### ISSUE THREAD

**Issue by ankushreddy** [hammerlab/guacamole#471]
Hi @ryan-williams @arahuja 

                          please find the error when am trying to run the spark-submit.

16/05/02 14:59:37 INFO BlockManager: BlockManager stopped
16/05/02 14:59:37 INFO BlockManagerMaster: BlockManagerMaster stopped
16/05/02 14:59:37 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
16/05/02 14:59:37 INFO SparkContext: Successfully stopped SparkContext
**Exception in thread "main" org.apache.spark.SparkException: Failed to register classes with Kryo**
        at org.apache.spark.serializer.KryoSerializer.newKryo(KryoSerializer.scala:128)
        at org.apache.spark.serializer.KryoSerializerInstance.borrowKryo(KryoSerializer.scala:273)
        at org.apache.spark.serializer.KryoSerializerInstance.<init>(KryoSerializer.scala:258)
        at org.apache.spark.serializer.KryoSerializer.newInstance(KryoSerializer.scala:174)
        at org.apache.spark.broadcast.TorrentBroadcast$.blockifyObject(TorrentBroadcast.scala:201)
        at org.apache.spark.broadcast.TorrentBroadcast.writeBlocks(TorrentBroadcast.scala:102)
        at org.apache.spark.broadcast.TorrentBroadcast.<init>(TorrentBroadcast.scala:85)
        at org.apache.spark.broadcast.TorrentBroadcastFactory.newBroadcast(TorrentBroadcastFactory.scala:34)
        at org.apache.spark.broadcast.BroadcastManager.newBroadcast(BroadcastManager.scala:63)
        at org.apache.spark.SparkContext.broadcast(SparkContext.scala:1326)
        at org.hammerlab.guacamole.reference.ReferenceBroadcast$.readFasta(ReferenceBroadcast.scala:73)
        at org.hammerlab.guacamole.reference.ReferenceBroadcast$.apply(ReferenceBroadcast.scala:154)
        at org.hammerlab.guacamole.commands.jointcaller.SomaticJoint$Caller$.run(SomaticJointCaller.scala:92)
        at org.hammerlab.guacamole.commands.jointcaller.SomaticJoint$Caller$.run(SomaticJointCaller.scala:80)
        at org.hammerlab.guacamole.commands.SparkCommand.run(SparkCommand.scala:10)
        at org.hammerlab.guacamole.commands.Command.run(Command.scala:46)
        at org.hammerlab.guacamole.Main$.main(Main.scala:68)
        at org.hammerlab.guacamole.Main.main(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
**Caused by: java.lang.ClassNotFoundException: org.hammerlab.guacamole.kryo.GuacamoleKryoRegistrar**

Hi could you please let me know if there is any way to filter the variants based on quality or is  there any way to get the qual filter and other missing information in the vcf files.

Thanks & Regards,
Ankush Reddy.

**Comment by ryan-williams** [comment]
Hey @ankushreddy, this looks like a bug! I recently (https://github.com/hammerlab/guacamole/pull/453) renamed the kryo registrar and didn't update [this place where we pass the class-name to Spark](https://github.com/hammerlab/guacamole/blob/b76b69d38dd918a7ae78ea033fc341139de0b14a/src/main/scala/org/hammerlab/guacamole/commands/SparkCommand.scala#L44); I'll send a PR to fix it immediately, thanks for catching!

**Comment by ankushreddy** [comment]
Thanks for looking into this @ryan-williams  by any chance do you have idea about filter the variants based on the quality or is there any way to get the information related to qual,filter that are missing in the outputs of the guacamole (in vcf file).

please find the sample output am talking about.

##fileformat=VCFv4.1
##Caller=Guacamole
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic depths for the ref and alt alleles">
##FORMAT=<ID=ADP,Number=1,Type=String,Description="allelic depth as num postiive strand / num total">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Total depth">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype quality">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="Phred scaled genotype likelihoods">
##FORMAT=<ID=RL,Number=1,Type=String,Description="Unnormalized log10 genotype posteriors">
##FORMAT=<ID=TRIGGERED,Number=1,Type=Integer,Description="Did this sample trigger a call">
##FORMAT=<ID=VAF,Number=1,Type=Integer,Description="Variant allele frequency (percent)">
##INFO=<ID=TRIGGER,Number=1,Type=String,Description="Which likelihood ratio test triggered call: POOLED and/or INDIVIDUAL">
##contig=<ID=chr11,length=135006516>
##parameter.anyAlleleMinSupportingPercent=3.0
##parameter.anyAlleleMinSupportingReads=2
##parameter.germlineNegativeLog10HeterozygousPrior=4.0
##parameter.germlineNegativeLog10HomozygousAlternatePrior=5.0
##parameter.maxAllelesPerSite=4
##parameter.somaticGenotypePolicy=presence
##parameter.somaticMaxGermlineErrorRatePercent=4.0
##parameter.somaticNegativeLog10VariantPrior=6.0
##parameter.somaticVafFloor=0.05
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  added_output
chr11   61202   .       G       T       .       .       TRIGGER=GERMLINE_POOLED GT:AD:ADP:DP:RL:VAF     0/1:0,2:G=0 T=2:2:[G/G]->-7.8087000 [G/T]->-6.7092700 [T/T]->-28
.397743:1.00
chr11   61367   .       A       G       .       .       TRIGGER=GERMLINE_POOLED GT:AD:ADP:DP:RL:VAF     0/1:0,2:A=0 G=2:2:[A/A]->-6.6998458 [A/G]->-5.8061800 [G/G]->-20
.898725:1.00
chr11   61399   .       TTT     T       .       .       TRIGGER=GERMLINE_POOLED GT:AD:ADP:DP:RL:VAF     0/1:0,2:TTT=0 T=2:2:[TTT/TTT]->-6.9994192 [TTT/T]->-4.6020600 [T
/T]->-5.0005817:1.00
chr11   61987   .       T       C       .       .       TRIGGER=GERMLINE_POOLED GT:AD:ADP:DP:RL:VAF     0/1:0,2:T=0 C=2:2:[T/T]->-8.5982688 [T/C]->-4.6020600 [C/C]->-5.
0000436:1.00
chr11   62795   .       A       G       .       .       TRIGGER=GERMLINE_POOLED GT:AD:ADP:DP:RL:VAF     0/1:0,2:A=0 G=2:2:[A/A]->-8.1990858 [A/G]->-5.8061800 [G/G]->-20
.998287:1.00
chr11   62943   .       A       G       .       .       TRIGGER=GERMLINE_POOLED GT:AD:ADP:DP:RL:VAF     0/1:0,2:A=0 G=2:2:[A/A]->-7.1997903 [A/G]->-5.5051500 [G/G]->-17
.198447:1.00



Thanks & Regards,
Ankush Reddy

**Comment by e5c** [comment]
Hey @ankushreddy, I believe you may be looking for the `--min-average-mapping-quality` or `--min-average-base-quality` command line args (see `org.hammerlab.guacamole.filters.SomaticGenotypeFilter`)
