### ISSUE TITLE
local invocation in README is broken

### ISSUE THREAD

**Issue by timodonnell** [hammerlab/guacamole#509]
Running the command in the README:

```
$ scripts/guacamole somatic-joint     \
  src/test/resources/synth1.normal.100k-200k.withmd.bam \     
  src/test/resources/synth1.tumor.100k-200k.withmd.bam    \
   --reference-fasta ~/sinai/data/b37.fasta    \
   --out /tmp/out.vcf
```

Gives me:

```
Found guac jar: target/guacamole-0.0.1-SNAPSHOT.jar
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
--> [Tue Jul 26 14:13:15 EDT 2016]: Guacamole starting.
2016-07-26 14:13:16 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2016-07-26 14:13:16 ERROR SparkContext:95 - Error initializing SparkContext.
com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'akka.version'
	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:124)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:145)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:151)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:159)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:164)
	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:206)
	at akka.actor.ActorSystem$Settings.<init>(ActorSystem.scala:169)
	at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:505)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:119)
	at org.apache.spark.util.AkkaUtils$.org$apache$spark$util$AkkaUtils$$doCreateActorSystem(AkkaUtils.scala:121)
	at org.apache.spark.util.AkkaUtils$$anonfun$1.apply(AkkaUtils.scala:53)
	at org.apache.spark.util.AkkaUtils$$anonfun$1.apply(AkkaUtils.scala:52)
	at org.apache.spark.util.Utils$$anonfun$startServiceOnPort$1.apply$mcVI$sp(Utils.scala:1988)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:141)
	at org.apache.spark.util.Utils$.startServiceOnPort(Utils.scala:1979)
	at org.apache.spark.util.AkkaUtils$.createActorSystem(AkkaUtils.scala:55)
	at org.apache.spark.SparkEnv$.create(SparkEnv.scala:266)
	at org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:193)
	at org.apache.spark.SparkContext.createSparkEnv(SparkContext.scala:288)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:457)
	at org.hammerlab.guacamole.commands.SparkCommand.createSparkContext(SparkCommand.scala:65)
	at org.hammerlab.guacamole.commands.SparkCommand.run(SparkCommand.scala:10)
	at org.hammerlab.guacamole.commands.Command.run(Command.scala:46)
	at org.hammerlab.guacamole.Main$.main(Main.scala:68)
	at org.hammerlab.guacamole.Main.main(Main.scala)
Exception in thread "main" com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'akka.version'
	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:124)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:145)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:151)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:159)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:164)
	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:206)
	at akka.actor.ActorSystem$Settings.<init>(ActorSystem.scala:169)
	at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:505)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:119)
	at org.apache.spark.util.AkkaUtils$.org$apache$spark$util$AkkaUtils$$doCreateActorSystem(AkkaUtils.scala:121)
	at org.apache.spark.util.AkkaUtils$$anonfun$1.apply(AkkaUtils.scala:53)
	at org.apache.spark.util.AkkaUtils$$anonfun$1.apply(AkkaUtils.scala:52)
	at org.apache.spark.util.Utils$$anonfun$startServiceOnPort$1.apply$mcVI$sp(Utils.scala:1988)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:141)
	at org.apache.spark.util.Utils$.startServiceOnPort(Utils.scala:1979)
	at org.apache.spark.util.AkkaUtils$.createActorSystem(AkkaUtils.scala:55)
	at org.apache.spark.SparkEnv$.create(SparkEnv.scala:266)
	at org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:193)
	at org.apache.spark.SparkContext.createSparkEnv(SparkContext.scala:288)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:457)
	at org.hammerlab.guacamole.commands.SparkCommand.createSparkContext(SparkCommand.scala:65)
	at org.hammerlab.guacamole.commands.SparkCommand.run(SparkCommand.scala:10)
	at org.hammerlab.guacamole.commands.Command.run(Command.scala:46)
	at org.hammerlab.guacamole.Main$.main(Main.scala:68)
	at org.hammerlab.guacamole.Main.main(Main.scala)
        2.09 real         2.46 user         0.23 sys

**Comment by timodonnell** [comment]
My guac jar built on July 11 does not have this issue so appears to have been introduced recently

**Comment by ryan-williams** [comment]
looking

**Comment by ryan-williams** [comment]
Looks like I inadvertently removed some `reference.conf` shading info in #482, and we're hitting [this](http://stackoverflow.com/a/31011315/544236).

Fix is incoming.
